// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs(title, content, user_id)
VALUES ($1, $2, $3)
    RETURNING id, title, content, user_id, created_at, updated_at
`

type CreateBlogParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	UserID  int32  `json:"user_id"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.createBlogStmt, createBlog, arg.Title, arg.Content, arg.UserID)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(username, email, password)
VALUES ($1, $2, $3)
    RETURNING id, username, email, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserRow struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Username, arg.Email, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (user_id, profile_image)
VALUES ($1, $2)
RETURNING id, user_id, profile_image
`

type CreateUserProfileParams struct {
	UserID       int32          `json:"user_id"`
	ProfileImage sql.NullString `json:"profile_image"`
}

type CreateUserProfileRow struct {
	ID           int32          `json:"id"`
	UserID       int32          `json:"user_id"`
	ProfileImage sql.NullString `json:"profile_image"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (CreateUserProfileRow, error) {
	row := q.queryRow(ctx, q.createUserProfileStmt, createUserProfile, arg.UserID, arg.ProfileImage)
	var i CreateUserProfileRow
	err := row.Scan(&i.ID, &i.UserID, &i.ProfileImage)
	return i, err
}

const deleteBlog = `-- name: DeleteBlog :exec
DELETE FROM blogs
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteBlog(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteBlogStmt, deleteBlog, id)
	return err
}

const getTotalUserCound = `-- name: GetTotalUserCound :one
SELECT COUNT(*) AS total FROM users
`

func (q *Queries) GetTotalUserCound(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getTotalUserCoundStmt, getTotalUserCound)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailIncludingPassword = `-- name: GetUserByEmailIncludingPassword :one
SELECT id, username, email, password, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmailIncludingPassword(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailIncludingPasswordStmt, getUserByEmailIncludingPassword, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByUserId = `-- name: GetUserProfileByUserId :one
SELECT id, user_id, profile_image, created_at, updated_at
FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetUserProfileByUserId(ctx context.Context, userID int32) (UserProfile, error) {
	row := q.queryRow(ctx, q.getUserProfileByUserIdStmt, getUserProfileByUserId, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProfileImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, title, content, user_id, created_at, updated_at
FROM blogs
ORDER BY id
`

func (q *Queries) ListBlogs(ctx context.Context) ([]Blog, error) {
	rows, err := q.query(ctx, q.listBlogsStmt, listBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, created_at, updated_at 
FROM users
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
